### PR TITLE
Limit the number of message

### LINKED ISSUE #6: Update add command
When List has the number of `MAX_ITEM` items 
- Return error message
- Ignore the message(Not to add into List)

### PR DESCRIPTION
**Pull request by chaspy**
Close: https://github.com/kamontia/kimetaro/issues/6

### CODE REVIEW

**Comment by chaspy** [comment]
Screenshot 2019-05-02 07 55 27

😎

**Comment by chaspy** [comment]
@kamontia 
Please review and merge

**Comment by chaspy** [comment]
```
May 01 16:05:06 kimetaro-pr-19 app/worker.1:  Traceback (most recent call last): 
May 01 16:05:06 kimetaro-pr-19 app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 255, in _run_event 
May 01 16:05:06 kimetaro-pr-19 app/worker.1:      await coro(*args, **kwargs) 
May 01 16:05:06 kimetaro-pr-19 app/worker.1:    File "kimetaro.py", line 46, in on_message 
May 01 16:05:06 kimetaro-pr-19 app/worker.1:      if len(LIST[message.channel.id]) >= MAX_ITEMS: 
```

😇

**Comment by kamontia** [comment]
@chaspy The error has disappeared.
It's no problem on my side. If you don't mind, it's ready to be merged into master.

**Comment by chaspy** [comment]
@kamontia 
Thanks! Please review/merge

**Comment by kamontia** [comment]
@chaspy LGTM 😄

**Pull request merged**
