### PR TITLE
Hello CircleCI 👋

### PR DESCRIPTION
**Pull request by chaspy**

### CODE REVIEW

**Comment by chaspy** [comment]
I added environment variables to CircleCI
Screenshot 2019-04-26 22 12 48

**Comment by chaspy** [comment]
Success in the branch 👍 
https://circleci.com/gh/kamontia/kimetaro/3

I'll revert e858940

**Comment by chaspy** [comment]
@kamontia 
Please review and merge

**Comment by kamontia** [comment]
Welcome to CI
@chaspy Thank you for quick job

**Pull request merged**
