### PR TITLE
Change message if list is empty

### LINKED ISSUE #5: Update list commands
- When List is empty, change return message

### PR DESCRIPTION
**Pull request by chaspy**
Close: https://github.com/kamontia/kimetaro/issues/5

### CODE REVIEW

**Comment by chaspy** [comment]
(@kamontia JFYI. It's not related in the PR)
~~If there is no Pull Request, review job failed
because PullRequest Number can't be gotten.
ref: https://circleci.com/gh/kamontia/kimetaro/104~~

~~Enabled `Only build pull requests` option.~~
Screenshot 2019-05-02 22 20 08

Disabled the option again.
The option *Only* build when opened pull request. so we can't rebuild CI 😢

**Comment by chaspy** [comment]
🙆 
Screenshot 2019-05-02 22 44 27

**Comment by chaspy** [comment]
@kamontia 
Please  review and merge

**Comment by kamontia** [comment]
@chaspy Please change "リストはからっぽや！" to "残念やったな！リストはからっぽや！", this is my request.

**Comment by chaspy** [comment]
😅

**Comment by chaspy** [comment]
Screenshot 2019-05-02 22 58 34

@kamontia 
Addressed. 4c0da1f 
Ready for review/merge again.

**Comment by kamontia** [comment]
@chaspy LGTM!!! NICE!!!

**Pull request merged**
